### ISSUE TITLE
[Suggestion][finalize] Do not install fake ticket if ticket with same title id already exists, or if title does not exist in title database

### ISSUE THREAD

**Issue by ZeroSkill1** [ihaveamac/custom-install#46]
In the case of an existing ticket, overwriting it doesn't change anything.
In the case of a title that does not exist in the title database, it would install a ticket that is going to be unused until it's deleted.

**Comment by ihaveamac** [comment]
I thought about doing the first one, it might help solve the d8e08019 error. Second one, I don't really know since it's not exactly hurting anything (there's a limit of 8192 tickets and nobody will ever come close to this amount in practice). Both cases will require a bunch more code to retrieve the ticket and title lists to verify. (Example: https://github.com/ihaveamac/faketik/blob/01d873804c67eb323079fd85f6a39e56bdcb171c/source/main.c#L29-L107) Not against doing it though, maybe when I'm bored.
